apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab-pv-2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/lab-data-2"
  persistentVolumeReclaimPolicy: Retain
