apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab-pvc
  namespace: storage-lab
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
