apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: large-pvc
  namespace: storage-lab
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # This exceeds our available PV capacity
