apiVersion: v1
kind: Service
metadata:
  name: storage-app-service
  namespace: storage-lab
spec:
  selector:
    app: storage-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
