apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-standalone-app
  labels:
    app: nginx-standalone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-standalone
  template:
    metadata:
      labels:
        app: nginx-standalone
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.3
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: NGINX_PORT
          value: "80"
