apiVersion: v1
kind: Service
metadata:
  name: nginx-standalone-service
  labels:
    app: nginx-standalone
spec:
  type: NodePort
  selector:
    app: nginx-standalone
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http
