apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: multi-tire-app
  labels:
    app: frontend
    tire: frontend
spec:
  selector:
    app: frontend
    tire: frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  type: NodePort

