apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-auto
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
